//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public book()
        {
            this.book_cart = new HashSet<book_cart>();
            this.book_order = new HashSet<book_order>();
            this.bookComment = new HashSet<bookComment>();
        }
    
        public int book_id { get; set; }
        public Nullable<int> type_id { get; set; }
        public int account { get; set; }
        public string picture_url { get; set; }
        public Nullable<decimal> price { get; set; }
        public string state { get; set; }
        public string introduction { get; set; }
        public Nullable<int> count { get; set; }
        public string province { get; set; }
        public string book_name { get; set; }
        public string author { get; set; }
        public string book_edition { get; set; }
    
        public virtual ICollection<book_cart> book_cart { get; set; }
        public virtual bookType bookType { get; set; }
        public virtual users users { get; set; }
        public virtual bookDetail bookDetail { get; set; }
        public virtual ICollection<book_order> book_order { get; set; }
        public virtual ICollection<bookComment> bookComment { get; set; }
    }
}
