//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookOrder
    {
        public bookOrder()
        {
            this.book_order = new HashSet<book_order>();
        }
    
        public int order_id { get; set; }
        public Nullable<int> buyer { get; set; }
        public Nullable<int> seller { get; set; }
        public string state { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> rece_id { get; set; }
    
        public virtual ICollection<book_order> book_order { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
        public virtual receiving receiving { get; set; }
    }
}
