//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class netHWEntities : DbContext
    {
        public netHWEntities()
            : base("name=netHWEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<book> book { get; set; }
        public DbSet<book_cart> book_cart { get; set; }
        public DbSet<book_order> book_order { get; set; }
        public DbSet<bookComment> bookComment { get; set; }
        public DbSet<bookDetail> bookDetail { get; set; }
        public DbSet<bookOrder> bookOrder { get; set; }
        public DbSet<bookType> bookType { get; set; }
        public DbSet<receiving> receiving { get; set; }
        public DbSet<shoppingCart> shoppingCart { get; set; }
        public DbSet<userRole> userRole { get; set; }
        public DbSet<users> users { get; set; }
    }
}
