//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shoppingCart
    {
        public shoppingCart()
        {
            this.book_cart = new HashSet<book_cart>();
        }
    
        public int cart_id { get; set; }
        public Nullable<int> account { get; set; }
        public Nullable<decimal> total_price { get; set; }
        public Nullable<int> total_quantity { get; set; }
    
        public virtual ICollection<book_cart> book_cart { get; set; }
        public virtual users users { get; set; }
    }
}
