//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.book = new HashSet<book>();
            this.bookComment = new HashSet<bookComment>();
            this.bookOrder = new HashSet<bookOrder>();
            this.bookOrder1 = new HashSet<bookOrder>();
            this.shoppingCart = new HashSet<shoppingCart>();
            this.users1 = new HashSet<users>();
            this.users2 = new HashSet<users>();
            this.userRole = new HashSet<userRole>();
        }
    
        public int account { get; set; }
        public string password { get; set; }
        public string nickname { get; set; }
        public string email { get; set; }
        public string tele_phone { get; set; }
        public string name { get; set; }
        public string sex { get; set; }
        public string picture_url { get; set; }
        public Nullable<int> rece_id { get; set; }
    
        public virtual ICollection<book> book { get; set; }
        public virtual ICollection<bookComment> bookComment { get; set; }
        public virtual ICollection<bookOrder> bookOrder { get; set; }
        public virtual ICollection<bookOrder> bookOrder1 { get; set; }
        public virtual receiving receiving { get; set; }
        public virtual ICollection<shoppingCart> shoppingCart { get; set; }
        public virtual ICollection<users> users1 { get; set; }
        public virtual ICollection<users> users2 { get; set; }
        public virtual ICollection<userRole> userRole { get; set; }
    }
}
