//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class book_order
    {
        public int order_id { get; set; }
        public int book_id { get; set; }
        public string state { get; set; }
        public Nullable<int> count { get; set; }
    
        public virtual book book { get; set; }
        public virtual bookOrder bookOrder { get; set; }
    }
}
